from setuptools import setup

setup(
    name='webcam-realtime-crop',
    version='',
    packages=['venv.lib.python3.7.site-packages.cv2', 'venv.lib.python3.7.site-packages.cv2.data',
              'venv.lib.python3.7.site-packages.numpy', 'venv.lib.python3.7.site-packages.numpy.ma',
              'venv.lib.python3.7.site-packages.numpy.ma.tests', 'venv.lib.python3.7.site-packages.numpy.doc',
              'venv.lib.python3.7.site-packages.numpy.fft', 'venv.lib.python3.7.site-packages.numpy.fft.tests',
              'venv.lib.python3.7.site-packages.numpy.lib', 'venv.lib.python3.7.site-packages.numpy.lib.tests',
              'venv.lib.python3.7.site-packages.numpy.core', 'venv.lib.python3.7.site-packages.numpy.core.tests',
              'venv.lib.python3.7.site-packages.numpy.f2py', 'venv.lib.python3.7.site-packages.numpy.f2py.tests',
              'venv.lib.python3.7.site-packages.numpy.tests', 'venv.lib.python3.7.site-packages.numpy.compat',
              'venv.lib.python3.7.site-packages.numpy.compat.tests', 'venv.lib.python3.7.site-packages.numpy.linalg',
              'venv.lib.python3.7.site-packages.numpy.linalg.tests', 'venv.lib.python3.7.site-packages.numpy.random',
              'venv.lib.python3.7.site-packages.numpy.random.tests',
              'venv.lib.python3.7.site-packages.numpy.random.tests.data',
              'venv.lib.python3.7.site-packages.numpy.testing', 'venv.lib.python3.7.site-packages.numpy.testing.tests',
              'venv.lib.python3.7.site-packages.numpy.testing._private',
              'venv.lib.python3.7.site-packages.numpy.distutils',
              'venv.lib.python3.7.site-packages.numpy.distutils.tests',
              'venv.lib.python3.7.site-packages.numpy.distutils.command',
              'venv.lib.python3.7.site-packages.numpy.distutils.fcompiler',
              'venv.lib.python3.7.site-packages.numpy.matrixlib',
              'venv.lib.python3.7.site-packages.numpy.matrixlib.tests',
              'venv.lib.python3.7.site-packages.numpy.polynomial',
              'venv.lib.python3.7.site-packages.numpy.polynomial.tests',
              'venv.lib.python3.7.site-packages.pyfakewebcam',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.idna',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pytoml',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.certifi',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet.cli',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib._backport',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.msgpack',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.util',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.backports',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.colorama',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib._trie',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.filters',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.lockfile',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.progress',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.requests',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.packaging',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.webencodings',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pkg_resources',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.req',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.vcs',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.utils',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.models',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.commands',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.operations',
              'venv.lib64.python3.7.site-packages.cv2', 'venv.lib64.python3.7.site-packages.cv2.data',
              'venv.lib64.python3.7.site-packages.numpy', 'venv.lib64.python3.7.site-packages.numpy.ma',
              'venv.lib64.python3.7.site-packages.numpy.ma.tests', 'venv.lib64.python3.7.site-packages.numpy.doc',
              'venv.lib64.python3.7.site-packages.numpy.fft', 'venv.lib64.python3.7.site-packages.numpy.fft.tests',
              'venv.lib64.python3.7.site-packages.numpy.lib', 'venv.lib64.python3.7.site-packages.numpy.lib.tests',
              'venv.lib64.python3.7.site-packages.numpy.core', 'venv.lib64.python3.7.site-packages.numpy.core.tests',
              'venv.lib64.python3.7.site-packages.numpy.f2py', 'venv.lib64.python3.7.site-packages.numpy.f2py.tests',
              'venv.lib64.python3.7.site-packages.numpy.tests', 'venv.lib64.python3.7.site-packages.numpy.compat',
              'venv.lib64.python3.7.site-packages.numpy.compat.tests',
              'venv.lib64.python3.7.site-packages.numpy.linalg',
              'venv.lib64.python3.7.site-packages.numpy.linalg.tests',
              'venv.lib64.python3.7.site-packages.numpy.random',
              'venv.lib64.python3.7.site-packages.numpy.random.tests',
              'venv.lib64.python3.7.site-packages.numpy.random.tests.data',
              'venv.lib64.python3.7.site-packages.numpy.testing',
              'venv.lib64.python3.7.site-packages.numpy.testing.tests',
              'venv.lib64.python3.7.site-packages.numpy.testing._private',
              'venv.lib64.python3.7.site-packages.numpy.distutils',
              'venv.lib64.python3.7.site-packages.numpy.distutils.tests',
              'venv.lib64.python3.7.site-packages.numpy.distutils.command',
              'venv.lib64.python3.7.site-packages.numpy.distutils.fcompiler',
              'venv.lib64.python3.7.site-packages.numpy.matrixlib',
              'venv.lib64.python3.7.site-packages.numpy.matrixlib.tests',
              'venv.lib64.python3.7.site-packages.numpy.polynomial',
              'venv.lib64.python3.7.site-packages.numpy.polynomial.tests',
              'venv.lib64.python3.7.site-packages.pyfakewebcam',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.idna',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pytoml',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.certifi',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet.cli',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib._backport',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.msgpack',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.util',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.backports',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.colorama',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib._trie',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.filters',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treewalkers',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treeadapters',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treebuilders',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.lockfile',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.progress',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.requests',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.packaging',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol.caches',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.webencodings',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pkg_resources',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.req',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.vcs',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.utils',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.models',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.commands',
              'venv.lib64.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.operations'],
    url='',
    license='',
    author='Jade Lacosse',
    author_email='jade@lacos.se',
    description=''
)
